== Примеры кода

В данном репозитории предложены компоненты бизнес процессов и соответствующая redux сущность

Данный код не является рабочим, только для демонстрации самого кода

== Все что было реализовано на последнем проекте "Камаз", но не было сказано

Разработана модульная архитектура - было принято решение разделить приложение на
несколько модулей. Основная структура сайта, модуль kamotive (который разрабатываем мы) и
другие модули, которые разрабатывает заказчик.
Задача была выполнена за счет создания 3 репозиториев и настройки для его сборки
с объединением роутов, редьюсеров и ядра приложения

Создана основная архитектура приложения (components, redux, routes, layouts)

Частичная настройка Gitlab-CI сборки и сборки Jenkins для стендов (проверка eslint, сборка приложения, проход тестов)

Полностью настройка webpack и eslint для проекта

Написание юнит и интеграционных тестов для приложения

Работа с дополнительными библиотеками Cadex, Bpmn, TimeLine, Chart.js, Material UI

Написание документации для других разработчиков
